### ISSUE TITLE
[flipchan]verify snapshot

### ISSUE THREAD

**Issue by flipchan** [DOTisDED/snapshot#5]

**Comment by flipchan** [comment]
todo:
install docs: 
apt install git-lfs
git lfs fetch --all

**Comment by flipchan** [comment]
![Screenshot_2024-02-13_09-25-30](https://github.com/DOTisDED/snapshot/assets/12517945/641e2086-94c0-4835-8cd2-c8d8ccca5887)
git lfs pull error

**Comment by flipchan** [comment]
```shell 
git clone https://github.com/DOTisDED/snapshot
Cloning into 'snapshot'...
remote: Enumerating objects: 239, done.
remote: Counting objects: 100% (239/239), done.
remote: Compressing objects: 100% (150/150), done.
remote: Total 239 (delta 99), reused 217 (delta 79), pack-reused 0
Receiving objects: 100% (239/239), 3.99 MiB | 22.71 MiB/s, done.
Resolving deltas: 100% (99/99), done.
Downloading archive/balances.json (2.8 MB)B | 45.46 MiB/s   
Error downloading object: archive/balances.json (dab5645): Smudge error: Error downloading archive/balances.json (dab56455ea40585740402ecd49187bc2e8df3c30115f5780850fb12d6cb4ce01): [dab56455ea40585740402ecd49187bc2e8df3c30115f5780850fb12d6cb4ce01] Object does not exist on the server: [404] Object does not exist on the server

Errors logged to /tmp/snapshot/.git/lfs/logs/20240213T093217.04153643.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: archive/balances.json: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

```

**Comment by flipchan** [comment]
node utils/snapshotAndAddTotals.cjs 
Starting process for block number: 1675172
📸 ⛓ Taking snapshot...
connecting...
querying account entries... page: 1
querying account entries... page: 2
Snapshot taken successfully.
✅ 🛎️ 📸 Snapshot taken successfully.
Summing totals in snapshot...
Error in main execution: TypeError: sumTotalsInSnapshot is not a function
sum total of 'Total' values: 13961540519559279239
number of accounts processed: 1232849

**Comment by flipchan** [comment]
node snapshot/snapshot-dot-assethub.cjs 
/tmp/snapshot/snapshot/snapshot-dot-assethub.cjs:17
    assetHubSnapshot: `./snapshot/dot-assethub-snapshot-${localConfig.relayBlockNumber}.json`,
                                                          ^

ReferenceError: Cannot access 'localConfig' before initialization
    at Object.<anonymous> (/tmp/snapshot/snapshot/snapshot-dot-assethub.cjs:17:59)

**Comment by flipchan** [comment]
node utils/snapshotAndAddTotals.cjs 
Starting process for block number: 18871235
📸 ⛓ Taking snapshot...
connecting...
2024-02-13 12:00:30        API/INIT: RPC methods not decorated: chainSpec_v1_chainName, chainSpec_v1_genesisHash, chainSpec_v1_properties
getting block hash: 18871235
connect opk
querying account entries... page: 8
Snapshot taken successfully.
✅ 🛎️ 📸 Snapshot taken successfully.
Summing totals in snapshot...
sum total of 'Total' values: 13961540519559279239
number of accounts processed: 1232849
Total sum from snapshot: undefined
Fetching total issuance from blockchain...
Querying the total issuance...
Total Issuance at block 18871235: 13957093143985979503
:/tmp/snapshot$ node utils/snapshotAndAddTotals.cjs 
Starting process for block number: 18871235
📸 ⛓ Taking snapshot...
connecting...
getting block hash: 18871235
connect opk
querying account entries... page: 8
Snapshot taken successfully.
✅ 🛎️ 📸 Snapshot taken successfully.
Summing totals in snapshot...
sum total of 'Total' values: 13961540519559279239
number of accounts processed: 1232849
Total sum from snapshot: undefined
Fetching total issuance from blockchain...
Querying the total issuance...
Total Issuance at block 18871235: 13957093143985979503

**Comment by flipchan** [comment]
```
creating snapshot
[1/4]running snapshotAndAddTotals.cjs  
Starting process for block number: 18871235
📸 ⛓ Taking snapshot...
connecting...
getting block hash: 18871235
connect opk
querying account entries... page: 8
Snapshot taken successfully.
✅ 🛎️ 📸 Snapshot taken successfully.
Summing totals in snapshot...
sum total of 'Total' values: 13961540519559279239
number of accounts processed: 1232849
Total sum from snapshot: undefined
Fetching total issuance from blockchain...
Querying the total issuance...
Total Issuance at block 18871235: 13957093143985979503
[2/4]running assethub snapshot  
Connecting to Polkadot Relay Chain...
Fetching parachain block hash for relay chain block 18871235...
Inspecting block extrinsics...
Examining extrinsic 0
Examining extrinsic 1
Statemint parachain entry not found in the relay chain block.
Parachain block hash not found.
[3/4]running bridgehub snapshot  
connecting...
querying account entries... page: 2
Snapshot taken successfully.
[4/4]running collectives snapshot  
connecting...
querying account entries... page: 2
Snapshot taken successfully.
done
```

**Comment by flipchan** [comment]
Finished searching blocks up to 18871235. Data written to /tmp/snapshot/crowdloan/crowdloan_contributions.json
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (node:fs:2164:5)
    at main (/tmp/snapshot/crowdloan/findAndFetchCrowdloan.cjs:125:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Data saved to ./nominationPools/accountsFromPools.json
[8/8]  re-allocate nomination pool member balances with main snapshot
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/tmp/snapshot/addPoolMembersToSnapshot.cjs'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v17.9.0
